sudo: required
services:
  - docker

before_install:
  - docker build -t octavia93/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true octavia93/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-197942941867"
  bucket_path: "docker"
  on:
    branch: master
  acess_key_id: $AWS_ACESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

